modmap:
  - name: Global
    remap:
      # Swap CapsLock, Ctrl_L
      CapsLock: Ctrl_L
      Ctrl_L: CapsLock
      Alt_l:
        held: Alt_l
        alone: Muhenkan
      Alt_r:
        held: Alt_r
        alone: Henkan

keymap:
  - name: Global
    remap:
      # Underscore without Shift
      RO: Shift-RO
