[tools]
cargo-binstall = "latest"
"cargo:sheldon" = "latest"
ghq = "latest"
node = "lts"
"npm:difit" = "latest"
"npm:dotenv-cli" = "latest"
"npm:opencode-ai" = "latest"
"npm:takt" = "latest"
pnpm = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
package_manager = "pnpm"
